### ISSUE TITLE
git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxWhisper#1]
I think similar to this issue https://github.com/zkmkarlsruhe/ofxTensorFlow2/issues/35#issuecomment-1451153776 I am not able to successfully run the `build_lib.sh`
I used the GitHub desktop to clone your add-on. 
![Screen Shot 2023-03-04 at 6 13 58 PM](https://user-images.githubusercontent.com/1054816/222932880-475a1653-f798-413f-97d1-c779de395b9a.jpg)

**Comment by roymacdonald** [comment]
I just pushed an update.
let me know if that fixed this issue

**Comment by stephanschulz** [comment]
`cp: directory ../libs/whisper_cpp/models does not exist`


![Screen Shot 2023-03-05 at 12 06 50 PM](https://user-images.githubusercontent.com/1054816/222975075-67c80453-0369-40bb-9a76-6b3f5c548c0b.jpg)

**Comment by roymacdonald** [comment]
fixed that. let me know if it works.

**Comment by stephanschulz** [comment]
the script seems to work now.

but upon compiling I get this error:

![Screen Shot 2023-03-05 at 7 38 03 PM](https://user-images.githubusercontent.com/1054816/222995688-4605ec37-9402-4140-9cc3-21590235be4c.jpg)

**Comment by roymacdonald** [comment]
that is because you need ofxSampleRate. do you have it installed? those missing symbols are from it

**Comment by danomatika** [comment]
@stephanschulz This issue is likely due to the fact that you are building for arm64, but libsamplerate.a included with ofxSampleRate is x86_64 only. If you scroll up your build output, you will probably see a yellow warning about this: https://github.com/roymacdonald/ofxSampleRate/issues/1

For now, I managed to get the example to run on my M1 machine by replacing the .a with one installed via homebrew:
1. If not installed, install libsamplerate: `brew install libsamplerate`
2. Copy libsamplerate.a to ofxSampleRate. In the ofxWhisper dir, run:
~~~
mv ../ofxSampleRate/libs/libsamplerate/lib/osx/libsamplerate.a ../ofxSampleRate/libs/libsamplerate/lib/osx/libsamplerate-bak.a
cp /opt/homebrew/lib/libsamplerate.a ../ofxSampleRate/libs/libsamplerate/lib/osx
~~~
3. If doing a release build, disable building for x86_64 by adding "x86_64" to Excluded Architectures in the project's Build Settings

**Comment by roymacdonald** [comment]
thanks @danomatika!
I though that @stephanschulz still had an intel mac, but from looking closer to the screenshots I see it is an arm mac.

**Comment by stephanschulz** [comment]
correct I am on an M1, macOS 12.6.3

**Comment by stephanschulz** [comment]
I guess at this point to make it work I will have to follow @danomatika steps. @roymacdonald is there any way your setup sh can already take care of this?
it's not that I do not want to do the work, it's more a question of streamlining the setup process :)

**Comment by roymacdonald** [comment]
Hi stephan, I will make a universal lib (both arm64 and x86_64) and upload it. I dont have an m1 mac so I cant really make a script with the steps that danomatika describes, in particular because I know that the paths where homebrew saves to are different for each architecture.

**Comment by stephanschulz** [comment]
`which brew` returns `/opt/homebrew/bin/brew` on my M1

**Comment by roymacdonald** [comment]
hi @stephanschulz I added a build_lib.sh script to ofxSampleRate. Can you please update ofxSampleRate and run this new script in it
once done update the ofxWhisper example with project generator

**Comment by stephanschulz** [comment]
I updated both addons.
but still get the same error
![Screen Shot 2023-03-07 at 7 44 56 AM](https://user-images.githubusercontent.com/1054816/223440427-2559a68d-9334-435b-a256-43345024712b.jpg)

**Comment by roymacdonald** [comment]
@stephanschulz did you run the build_libs.sh script in ofxSampleRate? not the one in ofxWhisper

**Comment by stephanschulz** [comment]
yes I did and now it works on an M1 MBP. thank you very much,
